---

- hosts: web
  become: yes
  gather_facts: true
  vars:
    kibana_host: 10.0.4.3:5601
    elastic_host: 10.0.3.4:9200
  tasks:

  - name: Копируем filebeat
    copy:
      src: /home/user/filebeat-7.17.11-amd64.deb
      dest: /home/user

  - name: Устанавливаем filebeat
    apt:
      deb: /home/user/filebeat-7.17.11-amd64.deb

  - name: Копируем конфиг filebeat
      template: 
      src: //home/user/111/filebeat.j2
      dest: /etc/filebeat/filebeat.yml

  - name: Перезапускаем сервисы

    systemd:
      name: filebeat
      enabled: yes
      state: started

